language: php

php:
  - 5.6

before_script:
  - composer self-update
  - composer update --prefer-source; composer install --dev --prefer-source;

script:
  - phpunit
  - php ./build/coverage-checker.php ./build/clover.xml 90